### ISSUE TITLE
Crashes soon after opening

### ISSUE THREAD

**Issue by mossymossmoss** [diamondburned/cchat-gtk#16]
Using the AUR version here. Upon opening and loging in, the application waits for a couple seconds and then crashes, providing the following error:  
`(cchat-gtk:769): Gtk-WARNING **: 21:00:48.764: Given child of type 'GtkBox' not found in GtkStack`

**Comment by diamondburned** [comment]
This is a warning. Warnings don't usually trigger crash. Can you paste the whole output?

**Comment by mossymossmoss** [comment]
Here's what I got:  

```
(cchat-gtk:2563): Gtk-WARNING **: 16:04:07.474: Given child of type 'GtkBox' not found in GtkStack
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	github.com/diamondburned/cchat-gtk/internal/gts.ExecAsync at github.com/diamondburned/cchat-gtk/internal/gts/gts.go:178
	github.com/diamondburned/cchat-gtk/internal/ui/service/session.(*Servers).load.func1 at github.com/diamondburned/cchat-gtk/internal/ui/service/session/servers.go:148
	runtime.goexit at runtime/asm_amd64.s:1371
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x560dc42dbc6e]

goroutine 1 [running]:
github.com/gotk3/gotk3/internal/closure.FuncStack.Panicf(0x560dc4ac74a0, 0xc000a18420, 0x13, 0xc000548060, 0x3, 0x3, 0x560dc460856d, 0x1b, 0xc000bff490, 0x1, ...)
	github.com/gotk3/gotk3@v0.5.3-0.20210326060404-6328e5470ece/internal/closure/funcstack.go:75 +0xb1f
github.com/gotk3/gotk3/internal/closure.FuncStack.TryRepanic(0x560dc4ac74a0, 0xc000a18420, 0x13, 0xc000548060, 0x3, 0x3)
	github.com/gotk3/gotk3@v0.5.3-0.20210326060404-6328e5470ece/internal/closure/funcstack.go:93 +0xfb
panic(0x560dc4b254a0, 0x560dc5a5aed0)
	runtime/panic.go:965 +0x1b9
github.com/diamondburned/cchat-gtk/internal/ui/service/session.(*Servers).setDone(0xc000a94000)
	github.com/diamondburned/cchat-gtk/internal/ui/service/session/servers.go:184 +0x4e
github.com/diamondburned/cchat-gtk/internal/ui/service/session.(*Servers).load.func1.1()
	github.com/diamondburned/cchat-gtk/internal/ui/service/session/servers.go:153 +0x4c
reflect.Value.call(0x560dc4ac74a0, 0xc000a18420, 0x13, 0x560dc45b67a5, 0x4, 0x560dc5b0a0d8, 0x0, 0x0, 0xc000bff9c0, 0x560dc39496ae, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0x560dc4ac74a0, 0xc000a18420, 0x13, 0x560dc5b0a0d8, 0x0, 0x0, 0x20, 0x40, 0xc000188e98)
	reflect/value.go:337 +0xb9
github.com/gotk3/gotk3/glib.goMarshal(0x7f6360002540, 0x7ffc585091d0, 0x560d00000000, 0x0, 0x0, 0x0)
	github.com/gotk3/gotk3@v0.5.3-0.20210326060404-6328e5470ece/glib/glib.go:269 +0xb71
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x560dc71fd0f0, 0x560d00000001, 0x560dc71e0b00, 0x0)
	_cgo_gotypes.go:1567 +0x4a
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc00011c2a0, 0xc0001182c0, 0x1, 0x1, 0x560dc71e0b00, 0x53)
	github.com/gotk3/gotk3@v0.5.3-0.20210326060404-6328e5470ece/glib/application.go:185 +0x96
github.com/gotk3/gotk3/glib.(*Application).Run(0xc00011c2a0, 0xc0001182c0, 0x1, 0x1, 0x0)
	github.com/gotk3/gotk3@v0.5.3-0.20210326060404-6328e5470ece/glib/application.go:185 +0x18d
github.com/diamondburned/cchat-gtk/internal/gts.Main(0x560dc4ce0150)
	github.com/diamondburned/cchat-gtk/internal/gts/gts.go:150 +0xcc
main.main()
	github.com/diamondburned/cchat-gtk/main.go:26 +0x2
```

**Comment by diamondburned** [comment]
This bug is fixed in the latest commit. Can you build that and try again?

**Comment by mossymossmoss** [comment]
Fixed!
