### ISSUE TITLE
Crash after clicking the disconnect button

### ISSUE THREAD

**Issue by ym1234** [diamondburned/cchat-gtk#2]
Happens constantly
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd47c12]

goroutine 1290 [running]:
github.com/diamondburned/cchat-gtk/internal/ui/service/session.(*Row).DisconnectSession.func1(0x12aef98, 0x0, 0x1)
    /home/ym/Drive/Projects/cchat-gtk/internal/ui/service/session/session.go:157 +0x32
github.com/diamondburned/cchat-gtk/internal/gts.Async.func1(0xc00083e1d0)
    /home/ym/Drive/Projects/cchat-gtk/internal/gts/gts.go:141 +0x27
created by github.com/diamondburned/cchat-gtk/internal/gts.Async
    /home/ym/Drive/Projects/cchat-gtk/internal/gts/gts.go:140 +0x3f
```

**Comment by diamondburned** [comment]
Fixed in latest.
